//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADORE
    {
        public int ID_USUARIO_ADMIN { get; set; }
        public string CORREO_ELECTRONICO_ADMIN { get; set; }
        public string NOMBRE_USUARIO_ADMIN { get; set; }
        public string NOMBRE_ADMIN { get; set; }
        public string APELLIDO_1_ADMIN { get; set; }
        public string APELLIDO_2_ADMIN { get; set; }
        public string TELEFONO_ADMIN { get; set; }
        public string CONTRASENNA_ADMIN { get; set; }
        public string TIPO_USUARIO_ADMIN { get; set; }
    }
}
