//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public int ID_CARRITO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public int CODIGO_PRODUCTO { get; set; }
        public int CANTIDAD { get; set; }
        public bool CARRITO_ACTIVO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
