//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN
    {
        public int ID_DETALLE_ORDEN { get; set; }
        public int CANTITDAD_DETALLE { get; set; }
        public int PRECIO_DETALLE { get; set; }
        public int ID_ORDEN_COMPRA { get; set; }
        public int CODIGO_PRODUCTO { get; set; }
    
        public virtual ORDER_COMPRA ORDER_COMPRA { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
