//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class METODO_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public METODO_PAGO()
        {
            this.CARRITO_COMPRAS = new HashSet<CARRITO_COMPRAS1>();
        }
    
        public long NUMERO_TARJETA { get; set; }
        public decimal NUMERO_EXPIRA_1 { get; set; }
        public decimal NUMERO_EXPIRA_2 { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public bool TARJETA_ACTICA { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO_COMPRAS1> CARRITO_COMPRAS { get; set; }
    }
}
